### ISSUE TITLE
How to place Critical Hit text in Attack section of unit info instead of Damage (as it was before)

### ISSUE THREAD

**Issue by Positiff88** [VladimirMakeev/D2ModdingToolset#215]
When I used mss32 v0.11 the Critical Hit text was shown in Attack section of unit encyclopedia, and it was nice. But now I'm switched to mss32 v0.14 and the Critical Hit text is shown in Damage and Power (Accuracy) sections [for example, **Damage: 80 (Critical Hit 20)**]. How can I move it back to Attack section? Is there any setting for this?

**Comment by UnveN** [comment]
@Positiff88 Yes that is true, the change was made due to new critical hit mechanics that allowed different damage and chance per attack so the simple indicator was replaced with detailed info.
Currently there is no way (other than changing the toolset code) to completely revert it back. However, you can manipulate `critHitAttack` and `critHitDamage` settings in textids.lua to shorten the text or completely remove the critical hit info from Damage and Power fields (you will have to add the "(Critical hit)" text manually to every attack name though to achieve previous behavior).

Or you can vote for a didicated setting to enable previous behavior (similar to already presented `displayInfiniteAttackIndicator`). It can be easily added in the next release of the toolset.

**Comment by Positiff88** [comment]
Please add a setting to enable previous behavior, which will show "(Critical hit)" text in attack description.
