### ISSUE TITLE
Possibility to sell items in any city and to buy potions (optional)

### ISSUE THREAD

**Issue by Positiff88** [VladimirMakeev/D2ModdingToolset#220]
It will be nice to have possibility to **sell items** in any city, so you can trade obtained valuables without the need to go to a merchant, which can be only one on the map and can be located very far away (so this trip only wastes time and prevents fast development). For example, it can be a special button in a city window, which you press and then select one of the items in your inventory, which will be **traded for money**.
Another interesting option is possibility to **buy potions** in all your cities (which is often needed, especially when you play by Mountain Clans with slow units taking damage almost in every battle, and are hard to obtain because usually there is one or few merchants on the map). It can be implemented as special button in a city window, which will show merchant's dialog, where you can **buy potions** and **sell items**. If it is possible to do, then the main suggestion to **sell items** in any city can be implemented as city merchant with empty inventory.

**Comment by VladimirMakeev** [comment]
This is a lot of work and personally I don't like the idea of merging city and merchant objects together because there are already not so many interactive objects on a strategic map in the game. Merchants in PvP and PvE scenarios can become points of interest, when player is forced to go and buy/sell items to get strategic andvantage. Same applies to mage towers, mercenaries and training camps.

There are some ideas for new interactive scenario map objects which I find interesting. I personally think it will be better to implement some of them instead of merging existing objects together. Amount of work to implement them looks the same as for merge.
Here's the list:
- Teleport
- Fortification. Same as city, but without garrison, unit hiring and inventory. Allows visiting leader to hide from spells and provides some armor bonus during siege. Does not convert nearby terrain. Occupies 2x2 area on a map.
- Resource marketplace. Allows visiting leader to exchange all resources between each other.
- 'Place of power'. Occupies 1x1 area. When controlled by playable race applies some modifier on stacks in area around it. Modifier can be buff for allies or debuff for enemies.
- 'Mage obelisk' 1x1 object that allows visiting leader to cast any of spells specified for obelisk.
- Object that converts terain in a large area when one of its tiles is captured
