### ISSUE TITLE
New areas

### ISSUE THREAD

**Issue by ShadoW2551** [VladimirMakeev/D2ModdingToolset#238]
Hi 
Is it possible to add new neutral terrains (but not as objects ) to the map editor to introduce more diversity for neutral units ;)?
(I am more concerned with instructions on how to accomplish this).
+How can you change the field of view for a single unit in the game files out of curiosity question ;)?

**Comment by VladimirMakeev** [comment]
Game engine tightly couples races (not players) with terrains. For each race mentioned in `GRace.dbf` there should be only one matching terrain `LTerrain.dbf` and vice versa. This is crucial for regeneration bonus on native terrain, for daily income, for spreading terrain after city capture etc.
Currently there are 5 playable races in the game and a neutrals. Neutrals contain many subraces such as greenskins, merfolk and dragons. If we want to add new terrain types specific to these subraces first of all we need to add additional unplayable races and move these subrace units from 'vanilla' neutrals. This way we can add a new terrains specific to these new 'neutral' races.

This is a lot of work, because not only it requires adding a new races to the game, but also treat them the same way neutrals are treated. Scenario Editor should also handle these new races as well: allow selecting units of these races, make them trigger events, paint new terrains etc.

I should also mention that because of a [tile format](https://github.com/VladimirMakeev/D2ModdingToolset/blob/master/mss32/include/midgardmapblock.h#L37-L43) it is possible to add only two new terrains without changing tiles.
There are only 3 bits allocated for terrain type allowing only 8 terrain and `LTerrain.dbf` already have 6 types which leaves us with only 2 new terrains possible.

If you look at Disciples II: Servants of the Dark or Guardians of the Light version of the game you can notice there are lot of unplayable races in `GRace.dbf`. I think developers had such idea with many neutral races and their terrains but later dropped it for some reason. These races are not handled by the engine, you can change their database records or even delete them without any observable effects and problems.

**Comment by ShadoW2551** [comment]
Thanks for the answer.
Another one is: What do I need to do to add more battlefield art (appearing during battles) ;)?

**Comment by VladimirMakeev** [comment]
You will need to patch server-side logic which decides theme for battle background image and client-side logic where one of the background images selected randomly depending on theme.
This is a bit challenging task since DisciplesGL by Verok also patches server side logic to fix units hitboxes and wide screen battle.

**Comment by ShadoW2551** [comment]
Hi 
Are there any ways to improve the bot in the game, even by expanding capitals more often or maybe there is a mod that does it hm ;)?

**Comment by VladimirMakeev** [comment]
Take a look at [MNS](https://norvezskayasemga.pro/mods/1) mod.
It changes AI related databases which makes it more agressive and gives it additional benefits.

**Comment by ShadoW2551** [comment]
Thanks!
Have a good day/night ;)
